language: python

sudo: false

python: 3.7

env:
    - TOXENV=flake8
    - TOXENV=py34-dj111-cms34
    - TOXENV=py35-dj111-cms34
    - TOXENV=py36-dj111-cms34
    - TOXENV=py37-dj111-cms34
    - TOXENV=py38-dj111-cms34
    - TOXENV=py34-dj21-cms34
    - TOXENV=py35-dj21-cms34
    - TOXENV=py36-dj21-cms34
    - TOXENV=py37-dj21-cms34
    - TOXENV=py38-dj21-cms34
    - TOXENV=py34-dj22-cms34
    - TOXENV=py35-dj22-cms34
    - TOXENV=py36-dj22-cms34
    - TOXENV=py37-dj22-cms34
    - TOXENV=py38-dj22-cms34
    - TOXENV=py34-dj111-cms35
    - TOXENV=py35-dj111-cms35
    - TOXENV=py36-dj111-cms35
    - TOXENV=py37-dj111-cms35
    - TOXENV=py38-dj111-cms35
    - TOXENV=py34-dj21-cms35
    - TOXENV=py35-dj21-cms35
    - TOXENV=py36-dj21-cms35
    - TOXENV=py37-dj21-cms35
    - TOXENV=py38-dj21-cms35
    - TOXENV=py34-dj22-cms35
    - TOXENV=py35-dj22-cms35
    - TOXENV=py36-dj22-cms35
    - TOXENV=py37-dj22-cms35
    - TOXENV=py38-dj22-cms35
    - TOXENV=py34-dj111-cms36
    - TOXENV=py35-dj111-cms36
    - TOXENV=py36-dj111-cms36
    - TOXENV=py37-dj111-cms36
    - TOXENV=py38-dj111-cms36
    - TOXENV=py34-dj21-cms36
    - TOXENV=py35-dj21-cms36
    - TOXENV=py36-dj21-cms36
    - TOXENV=py37-dj21-cms36
    - TOXENV=py38-dj21-cms36
    - TOXENV=py34-dj22-cms36
    - TOXENV=py35-dj22-cms36
    - TOXENV=py36-dj22-cms36
    - TOXENV=py37-dj22-cms36
    - TOXENV=py38-dj22-cms36
    - TOXENV=py34-dj111-cms37
    - TOXENV=py35-dj111-cms37
    - TOXENV=py36-dj111-cms37
    - TOXENV=py37-dj111-cms37
    - TOXENV=py38-dj111-cms37
    - TOXENV=py34-dj21-cms37
    - TOXENV=py35-dj21-cms37
    - TOXENV=py36-dj21-cms37
    - TOXENV=py37-dj21-cms37
    - TOXENV=py38-dj21-cms37
    - TOXENV=py34-dj22-cms37
    - TOXENV=py35-dj22-cms37
    - TOXENV=py36-dj22-cms37
    - TOXENV=py37-dj22-cms37
    - TOXENV=py38-dj22-cms37

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
